[package]
name = "flatcitybuf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "24.3.25"
byteorder = "1.5.0"
cjseq = { git = "https://github.com/HideBa/cjseq", branch = "develop" }
tempfile = "3.14.0"
serde_json = "1.0.133"

[[bin]]
name = "read"
path = "src/bin/read.rs"
