[package]
name = "fcb_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
fcb_core = { path = "../fcb_core", default-features = false }
clap = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
