name: Rust CI

on:
  push:
    branches: [main]
    paths:
      - "src/rust/**"
      - ".github/workflows/ci.yaml"
  pull_request:
    branches: [main]
    paths:
      - "src/rust/**"
      - ".github/workflows/ci.yaml"

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/rust

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src/rust
          shared-key: "fcb-rust-ci"

      - name: Check all
        run: make check-common
    # - name: Run tests
    #   run: cargo test --all-features --verbose

    # - name: Check formatting
    #   run: cargo fmt --all -- --check

    # - name: Run clippy
    #   run: cargo clippy --all-targets --all-features -- -D warnings

    # - name: Build
    #   run: cargo build --verbose
